apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-events-infra
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/shabbirsaifee92/liquibase-workflow.git
    targetRevision: HEAD
    path: helm/argo-events-infra
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    # syncOptions:
    # - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: liquibase-workflow
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/shabbirsaifee92/liquibase-workflow.git
    targetRevision: HEAD
    path: helm/liquibase-workflow
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    # syncOptions:
    # - CreateNamespace=true
  # Depends on argo-events-infra being synced first
  ignoreDifferences:
  - group: argoproj.io
    kind: WorkflowTemplate
    jsonPointers:
    - /status
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-database
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/shabbirsaifee92/liquibase-workflow.git
    targetRevision: HEAD
    path: helm/app-database
    helm:
      valueFiles:
      - values.yaml
      # You can add app-specific values file
      # - values-myapp.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  # Depends on liquibase-workflow being synced first
  ignoreDifferences:
  - group: ""
    kind: ConfigMap
    jsonPointers:
    - /metadata/annotations