apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.appName }}-db-config
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.appName }}
    type: db-config
    workflows.argoproj.io/configmap-type: Parameter
data:
  liquibase-image: {{ .Values.database.liquibaseImage }}
  database-url: {{ .Values.database.url }}
  changelog-file: {{ .Values.database.changelog }}
  context: {{ .Values.database.context }}