# EventSource for watching ConfigMap changes
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: {{ .Values.eventSource.name }}
  namespace: {{ .Values.namespace }}
spec:
  template:
    serviceAccountName: {{ .Values.serviceAccount.name }}
  eventBusName: {{ .Values.eventBus.name }}
  resource:
    configmap-watcher:
      namespace: {{ .Values.namespace }}
      group: ""
      version: v1
      resource: configmaps
      eventTypes:
        - UPDATE
      filter:
        labels:
          - key: "type"
            operation: "=="
            value: "db-config"
---
# Sensor for triggering workflows
# Sensor for triggering workflows
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: {{ .Values.sensor.name }}
  namespace: {{ .Values.namespace }}
spec:
  template:
    serviceAccountName: {{ .Values.serviceAccount.name }}
  eventBusName: {{ .Values.eventBus.name }}
  dependencies:
    - name: config-updated
      eventSourceName: {{ .Values.eventSource.name }}
      eventName: configmap-watcher
  triggers:
    - template:
        name: workflow-trigger
        k8s:
          operation: create
          parameters:
            - src:
                dependencyName: config-updated
                dataKey: body.metadata.name
              dest: spec.arguments.parameters.0.valueFrom.configMapKeyRef.name
              dest: spec.arguments.parameters.1.valueFrom.configMapKeyRef.name
              dest: spec.arguments.parameters.2.valueFrom.configMapKeyRef.name
              dest: spec.arguments.parameters.3.valueFrom.configMapKeyRef.name
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: liquibase-pipeline-
                namespace: {{ .Values.namespace }}
              spec:
                workflowTemplateRef:
                  name: {{ .Values.workflowTemplate.name }}
                arguments:
                  parameters:
                  - name: liquibase-image
                    valueFrom:
                      configMapKeyRef:
                        name: myapp-db-config
                        key: liquibase-image
                  - name: database-url
                    valueFrom:
                      configMapKeyRef:
                        name: myapp-db-config
                        key: database-url
                  - name: changelog-file
                    valueFrom:
                      configMapKeyRef:
                        name: myapp-db-config
                        key: changelog-file
                  - name: context
                    valueFrom:
                      configMapKeyRef:
                        name: myapp-db-config
                        key: context